include:
  - proxy.yaml

services:
  # ============================================
  # MySQL база данных (172.20.0.10:3306)
  # ============================================
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}     # .env: YtReWq4321 
      MYSQL_DATABASE: ${MYSQL_DATABASE}               # .env: virtd
      MYSQL_USER: ${MYSQL_USER}                       # .env: app
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}               # .env: QwErTy1234  
    networks:
      backend:
        ipv4_address: 172.20.0.10                     # IP из условия задачи
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ============================================
  # Python FastAPI приложение (172.20.0.5:5000)
  # ============================================
  web:
    build:
      context: .                        # Где искать Dockerfile
      dockerfile: Dockerfile.python     # Какой Dockerfile использовать
    container_name: shvirtd-example-python-web # Имя контейнера (для docker ps/logs)
    restart: unless-stopped             # Перезапуск при ошибках
    depends_on:
      db:
        condition: service_healthy      # Ждём, пока MySQL станет здоровым
    environment:
      # Переменные для подключения к БД (отличаются от значений по умолчанию в main.py)
      DB_HOST: "db"                     # Сетевое имя сервиса db 172.20.0.10
      DB_USER: ${MYSQL_USER}            # Из .env: app
      DB_PASSWORD: ${MYSQL_PASSWORD}    # Из .env: QwErTy1234
      DB_NAME: ${MYSQL_DATABASE}        # Из .env: virtd
    # Порт 5000 НЕ публикуем на хост - клиент обязан идти через Nginx (порт 8090)
    networks:
      backend:                         # Bridge-сеть из условия
        ipv4_address: 172.20.0.5       # Фиксированный IP из условия
    # Healthcheck встроен в Dockerfile.python

  # ============================================
  # ПЕРЕОПРЕДЕЛЯЕМ ingress-proxy ИЗ proxy.yaml
  # ============================================
  #ingress-proxy:
  #  image: nginx:latest
  #  container_name: nginx
  #  restart: unless-stopped
  #  ports:
  #    - "8090:8090"                              # ← Публикуем порт 8090
  #  networks:
  #    backend:
  #      ipv4_address: 172.20.0.20                # ← Добавляем в сеть backend
  #  volumes:
  #    - ./nginx/ingress/default.conf:/etc/nginx/conf.d/default.conf:ro
  #    - ./nginx/ingress/nginx.conf:/etc/nginx/nginx.conf:ro
    #depends_on:
    #  reverse-proxy:
    #    condition: service_healthy
    #healthcheck:
    #  test: ["CMD", "nginx", "-t"]
    #  interval: 30s
    #  timeout: 5s
    #  retries: 3


volumes:
  mysql_data:
